services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: server
    ports:
      - "5000:5000"
    restart: unless-stopped

  client:
    build:
      context: .
      dockerfile: Dockerfile
      target: client
    command: ["./build/client"]
    depends_on:
      - server
    stdin_open: true
    tty: true
