name: System Tests

on:
  push:
    paths-ignore:
      - "README.md"
      - ".gitignore"
      - ".dockerignore"
      - "Makefile"
      - "docs/*"
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  test_avl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Compile Test
        run: g++ -std=c++17 -Wall -Wextra tests/test_avl.cpp src/storage/avl.cpp -Iinclude -o test_avl

      - name: Runtime Test
        run: ./test_avl

  test_heap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Compile Test
        run: g++ -std=c++17 -Wall -Wextra tests/test_avl.cpp src/storage/avl.cpp -Iinclude -o test_avl

      - name: Runtime Test
        run: ./test_avl
